# Generated by Django 3.1.5 on 2021-01-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20210124_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateTimeField(),
        ),
    ]
