# Generated by Django 3.1.5 on 2021-01-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
